{{- /* deploy/helm/templates/service.yaml */ -}}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "daisi-wa-events-processor.fullname" . }}
  labels:
    {{- include "daisi-wa-events-processor.labels" . | nindent 4 }}
  # Optional annotations can be added here
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    {{- include "daisi-wa-events-processor.selectorLabels" . | nindent 4 }} 