global:
  scrape_interval: 15s

scrape_configs:
  - job_name: 'nats'
    static_configs:
      - targets: ['nats:8222'] # NATS built-in monitoring endpoint

  - job_name: 'nats_exporter'
    static_configs:
      - targets: ['nats_exporter:7777'] # NATS exporter endpoint

  - job_name: 'tenant_app_A'
    # Assuming your tenant apps expose metrics on port 2112 at /metrics
    # Adjust the port and path if necessary.
    # Docker Compose service discovery will resolve 'tenant_app_A' to all replicas.
    metrics_path: /metrics  # Explicitly define the metrics path
    dns_sd_configs:
      - names:
          - tenant_app_A
        type: A
        port: 8080 # <-- Changed from 2112 to 8080

  - job_name: 'tenant_app_B'
    metrics_path: /metrics # Explicitly define the metrics path
    dns_sd_configs:
      - names:
          - tenant_app_B
        type: A
        port: 8080 # <-- Changed from 2112 to 8080
          
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090'] 